### ISSUE TITLE
Grids for Australia

### ISSUE THREAD

**Issue by alexgleith** [NaturalGIS/ntv2_transformations#21]
Hey folks

I'm doing some work with ICSM Australia and I have the current Australian grids working in your master branch, and will be implementing the new 2020 grid after its' release.

I note that the master branch requires QGIS 3.0, and wonder whether there is any way to backport to previous versions of QGIS? I'd like to create a PR soon and to get the Australian grids into the plugin soon, or at the latest, after the new datum is released (March-ish).

Is it possible to get a new version of the plugin released for QGIS 2.XX?

**Comment by gioman** [comment]
@alexgleith Hi, the plugin works fine on on qgis >= 2.14 and was already ported also to qgis3 (kudos @alexbruy). Just install in on 2.14 and above using the QGIS plugin installer.

You are welcome to do a PR in order to add those transformations for Australia. The grids (the binary files) and sample data must be added here:

https://github.com/NaturalGIS/ntv2_transformations_grids_and_sample_data

Cheers!

**Comment by gioman** [comment]
http://plugins.qgis.org/plugins/ntv2_transformations/

**Comment by alexgleith** [comment]
Hi @gioman, the reason I asked is that the metadata in master here says it requires version >3.0 https://github.com/NaturalGIS/ntv2_transformations/blob/master/metadata.txt#L7

So, if I create a PR on master, I'm concerned that it wont make it in to the current version of the plugin.

**Comment by gioman** [comment]
@alexgleith I created a new branch

https://github.com/NaturalGIS/ntv2_transformations/tree/qgis2_comp

**Comment by alexgleith** [comment]
Thanks, @gioman. I'll set up a PR there soon, as well as in the other repo.
