### ISSUE TITLE
Croatia - ntv2 grid

### ISSUE THREAD

**Issue by dracic** [NaturalGIS/ntv2_transformations#5]
We would appreciate if you consider putting Croatia to your plugin. NTV2 files (links at the bottom):

http://geosinjal.blogspot.com/2012/12/kreiranje-ntv2-grid-datoteke-za.html

We need transformations from HKDS Zone 5 & 6 (not in EPSG database) - 

HDKS 5.zona:
+proj=tmerc +pm=greenwich +lat_0=0 +lon_0=15 +k=0.9999 +x_0=5500000 +y_0=0 +ellps=bessel +towgs84=550.499,164.116,475.142,5.80967,2.07902,-11.62386,0.99999445824 +units=m
HDKS 6.zona:
+proj=tmerc +pm=greenwich +lat_0=0 +lon_0=18 +k=0.9999 +x_0=6500000 +y_0=0 +ellps=bessel +towgs84=550.499,164.116,475.142,5.80967,2.07902,-11.62386,0.99999445824 +units=m

to HTRS96/Croatia TM - EPSG:3765

more on our projections:

http://wiki.osgeo.org/wiki/Croatia/Kratki_vodici/transformacija_koordinata_cs2cs

**Comment by gioman** [comment]
Hi,
is the HRNTv2.gsb grid file good for transforming both HKDS5 and HKDS6 to EPSG:3765?

Can you provide a sample of data so I can check if the transformation is working ok? Ideally I need a vector layer in two copies, in this case HKDS5 (or 6) and EPSG:3765 in order to check the error/difference there is reprojecting with proj parameters and then the difference after creating the transformed copy with the ntv2 grid. Cheers!

**Comment by dracic** [comment]
Hi,

yes HRNTv2.gsb is good for both HDKS5 & HDKS6 (a had a typo - it is not HKDS), and many of use use it this way, for example in QGIS:

HDKS5
+proj=tmerc +k=0.9999 +lon_0=15 +no_defs +x_0=5500000 +ellps=bessel +nadgrids /usr/share/proj/HRNTv2.gsb +units=m +lat_0=0 +wktext +y_0=0

HDKS6
+proj=tmerc +k=0.9999 +lon_0=18 +no_defs +x_0=6500000 +ellps=bessel +nadgrids /usr/share/proj/HRNTv2.gsb +units=m +lat_0=0 +wktext +y_0=0

I created 3 shapefiles - htrs (in EPSG:3765), HDKS(in HDKS5) and hdks5-ntv2 (reprojected with projection definitions configured as above) : https://www.dropbox.com/s/6474ruynblngch9/shapes.zip?dl=0

It should be noted that this is an "unofficial" version of a grid file, since we don't have and cannot use the one that has been created by State Geodetic Administration.

Thanks!

Best regards

**Comment by mmiler** [comment]
Hi,
Thank you for considering adding this grid file into your project. I think it will be very useful for Croatian spatial data users.
I would just like to give a brief overview. HRNTv2.gsb is not official Croatian grid file. The official grid file is proprietary and cannot be obtained because it is embedded in one software which is owned by our (Croatian) State Geodetic Office. This grid file (HRNTv2.gsb) was reversed engineered using that software and I have tested it thoroughly and got maximum of 5mm error between official application and this grid file using proj4. The error was mostly around 2 mm.
The projection parameters that @dracic was mentioning are global for Croatia and have an error off around 1 meter (depending on area), so comparing them with this grid file would not be useful because this grid file transformation is in the range of millimeters. More accurate parameters do exist but they are not for the whole of Croatia but only parts and they are used anymore because of this grid file exists.
Although this is not an official grid file, everybody is using it because proj4 supports NTv2 grid files and with that, most of the applications (like QGIS) can be used for transforming the data.
HRNTv2.gsb grid file is the best way to transform coordinate in Croatia from HDKS5 and HDKS6 zone to EPSG:3765 or any other coordinate system.

I hope this helps :)
Best regards,
Mario

**Comment by gioman** [comment]
I have pushed a new version of the plugin that includes the above grid/transformation. Before publishing in the qgis plugins repo I would appreciate a test because I'm really unsure about the results. Download it here https://github.com/NaturalGIS/ntv2_transformations/archive/master.zip

**Comment by mmiler** [comment]
Hi,
thank you. I have tested it and I confirm that is works.

Best regards,
Mario

**Comment by gioman** [comment]
ok, I already uploaded the new version to the qgis repository.

**Comment by dracic** [comment]
Thank you!
